apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensure-guaranteed-qos-class
spec:
  rules:
  - name: add-default-limits-and-requests
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: AnyIn
        value:
        - CREATE
        - DELETE
    mutate:
      foreach: 
      - list: "request.object.spec.[ephemeralContainers, initContainers, containers]"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              resources:
                limits:
                  +(memory): 500Mi
                  +(cpu): 200m
                requests:
                  +(memory): 100Mi
                  +(cpu): 100m
